name: CI

on:
  push:
  pull_request:
  workflow_dispatch: 

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: rustree-windows-x64
        path: |
          target/release/locales
          target/release/rt.exe
    
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Copy shell script
      run: |
        cp *.sh /target/release/*.sh
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: rustree-linux-x64
        path: |
          target/release/locales
          target/release/rt
          target/release/*.sh
